-- Disable RLS on all tables
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE mentees DISABLE ROW LEVEL SECURITY;
ALTER TABLE mentors DISABLE ROW LEVEL SECURITY;
ALTER TABLE signals DISABLE ROW LEVEL SECURITY;
ALTER TABLE signalChat DISABLE ROW LEVEL SECURITY;
ALTER TABLE signalChatUsers DISABLE ROW LEVEL SECURITY;
ALTER TABLE signalMessages DISABLE ROW LEVEL SECURITY;
ALTER TABLE forum_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE forum_responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE forum_bookmarks DISABLE ROW LEVEL SECURITY;
ALTER TABLE connections DISABLE ROW LEVEL SECURITY;
