import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <nav className='navigation-bar'>
          <Link href="/dashboard">
            <button className='nav-button' style={{margin:"20px"}}>
              Home
            </button>
          </Link>
          <Link href="/forums">
            <button className='nav-button' style={{margin:"20px"}}>
              Forums
            </button>
          </Link>
          <Link href="/chatrooms">
            <button className='nav-button' style={{margin:"20px"}}>
              Chatrooms
            </button>
          </Link>
        </nav>
        
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
